name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  SwiftLint:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.1.0
       
  Test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
        with:
          lfs: 'true'
      - name: Xcode Select
        uses: devbotsxyz/xcode-select@v1.0.0
        with:
          version: "12.0"
          beta: false
      - name: Resolve Swift Package Manager Dependencies
        run:  xcodebuild -resolvePackageDependencies
      - name: Build and Test
        run: xcodebuild -project SwiftDIDemo/SwiftDIDemo.xcodeproj -scheme SwiftDIDemo -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone SE (2nd generation)" build
